# Generated by Django 2.1.1 on 2018-11-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attackip', models.CharField(max_length=20)),
                ('attacktime', models.DateTimeField()),
                ('method', models.CharField(max_length=10)),
                ('path', models.TextField()),
                ('headers', models.TextField()),
                ('post', models.TextField()),
                ('get', models.TextField()),
                ('attacktype', models.TextField()),
                ('response', models.TextField()),
            ],
        ),
    ]
