# Generated by Django 2.1.1 on 2018-09-21 07:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='response',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
