# Generated by Django 2.1.1 on 2018-12-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='response',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='log',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
